name: Linux build develop

on: [push]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ubuntu-latest-QtCache
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          modules: 'qtcore qtgui qtquickcontrols2'
          
      - name: Build QuickQanava Ubuntu qmake
        run:
          qmake quickqanava.pro
        shell: bash
