name: Win64 build master

on:
  push:
    branches: [master, b/#175-msvc-build]
  pull_request:
    branches: [master]

jobs:
  test-build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.4.1'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: '${{ github.workspace }}/example/'
          install-deps: 'true'
          modules: 'qtcore qtgui qtquickcontrols2 core5compat'
          cache: 'false'
          cache-key-prefix: 'install-qt-action'

      - name: Run CMake
        shell: bash
        run: cmake
        working-directory: ${{runner.workspace}}
 
      - name: Compiling Holograph
        if: steps.hlg-build-cache.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          echo "Calling vcvarsall.exe..."
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{matrix.config.platform}}
          echo "Moving to build folder..."
          echo "NMAKE..."
          set CL=/MP & rem "Enabling multi-threading (max. available)"
          nmake 
