name: Linux build develop

on: [push]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ubuntu-latest-QtCache
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          modules: 'qtcore qtgui qtquickcontrols2'
          setup-python: false
      - name: Clone QuickQanava
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Build QuickQanava Ubuntu qmake
        run: |
          qmake -makefile -o ./../build/Makefile quickqanava.pro
          cd ../build
          make -j4
        working-directory: ./         
        shell: bash
